### ISSUE TITLE
Can you add a  example -- operation  mutation

### ISSUE THREAD

**Issue by liaofangcai** [maxmart/graphql-java-relay-router#1]
hello. In the GraphQLTest.java file. Can you add a  example about operation of mutation?

**Comment by maxmart** [comment]
Hello.
There are mutations already. 
On line 147:
https://github.com/maxmart/graphql-java-relay-router/blob/master/src/net/cupmanager/graphql/GraphQLTest.java#L147

**Comment by liaofangcai** [comment]
thanks
